# Use an OpenJDK base image
FROM openjdk:17-jdk-alpine

# Set the working directory for the application
WORKDIR /app

# Copy the compiled JAR of your Spring Boot project into the container
COPY target/Gifts-From-History-E-Commerce-0.0.1-SNAPSHOT.jar /app/Gifts-From-History-E-Commerce-0.0.1-SNAPSHOT.jar

# Expose the port on which the Spring Boot application will run
EXPOSE 8080

# Set the environment variables for Spring Boot application configuration
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=update
ENV SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/gifts-from-history-e-commerce?useSSL=false&serverTimezone=UTC
ENV SPRING_DATASOURCE_USERNAME=root
ENV SPRING_DATASOURCE_PASSWORD=root
ENV SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

# Define the command to run the Spring Boot application when the container starts
CMD ["java", "-jar", "Gifts-From-History-E-Commerce-0.0.1-SNAPSHOT.jar"]
