# Use a Node.js base image
FROM node:14

# Create a directory for the application
WORKDIR /app

# Copy package.json and package-lock.json files
COPY ./Gifts-From-History-E-Commerce.Client/gifts-from-history-e-commerce/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
